---
title: "Data_Project"
output: html_document
---
```{r}
library(tidyverse)
library(readr)
library(lubridate)
library(reshape2)
library(dplyr)
```

```{r}
NADAC_data_2024 <- read.csv("https://download.medicaid.gov/data/nadac-national-average-drug-acquisition-cost-10-16-2024.csv")

```
```{r}
Drug_Bank_Interacts <- read.delim("~/DRUGS/ChCh-Miner_durgbank-chem-chem.tsv", header=FALSE)
Drug_NDC_PropreitaryName <- read.csv("~/DRUGS/20220906_product.csv")
Drug_Prices <- read.csv("~/DRUGS/Medicaid_Spending_by_Drug_2022.csv")
```
```{r}
Undup_Drug_Prices <- Drug_Prices[ !duplicated(Drug_Prices$Brnd_Name),]
Undup_Drug_Prices

NoNA_Undup_Drug_Prices <- na.omit(Undup_Drug_Prices)
NoNA_Undup_Drug_Prices
```

```{r}
 Longer_Prices <- NoNA_Undup_Drug_Prices %>%
 pivot_longer(
   Tot_Spndng_2018:Avg_Spnd_Per_Clm_2022,
   names_to = "heads"
 )
Longer_Prices$year <- lapply(Longer_Prices$heads, function (x) stringr::str_match(x, "(\\d+)")[1])
Longer_Prices$type <- lapply(Longer_Prices$heads, function (x) stringr::str_match(x, "(.+)(?=\\_\\d{4})")[1])
Longer_Prices$heads <- NULL
Longer_Prices$year <- as.numeric(Longer_Prices$year)
Longer_Prices$type <- as.character(Longer_Prices$type)
```

```{r}
Spread_Prices <- spread(Longer_Prices, type, value)
```


```{r}
Medicine_Details <- subset(Medicine_Details, select = -c(Medicine.Name, Uses, Side_effects, Image.URL))

Medicine_Details$Composition <- stringr::str_remove_all(Medicine_Details$Composition, "\\([^)]*\\)")

reviews_clean <- data.frame(drug = Medicine_Details$Composition)
 
efun <- function(x) {
  d <- filter(Medicine_Details, Composition == x)
  sum(d$Excellent.Review..)
}

afun <- function(x) {
  d <- filter(Medicine_Details, Composition == x)
  sum(d$Average.Review..)
}

pfun <- function(x) {
  d <- filter(Medicine_Details, Composition == x)
  sum(d$Poor.Review..)
}

reviews_clean$excellent <- lapply(reviews_clean$drug, efun)

reviews_clean$average <- lapply(reviews_clean$drug, afun)

reviews_clean$poor <- lapply(reviews_clean$drug, pfun)

reviews_clean <- reviews_clean[ !duplicated(reviews_clean$drug),]
reviews_clean


  
#Medicine_Details_test <- Medicine_Details[stringr::str_extract(Medicine_Details$Composition, coll("Apixiban", ignore_case = TRUE)), ]
                    
```



# Merging data



```{r}
NewName1 <- data.frame( Medicine_Details, "Brnd_Name" = sapply(strsplit(Medicine_Details$Medicine.Name, split = " ", fixed = TRUE), function(x) {x [1] })  )

mergedData <- full_join(NoNA_Undup_Drug_Prices, NewName1, by = "Brnd_Name")

```


```{r}
DDI_data <- read.csv("~/DRUGS/data of multiple-type drug-drug interactions/DDI_data.csv")

DDI_data_test <- filter(DDI_data, drug1_name == "Apixaban")

reviews_clean <- as.data.frame(reviews_clean)
reviews_clean$drug <- trimws(reviews_clean$drug)

reviews_test <- filter(reviews_clean, drug == "Apixaban")


Joined_DDI_Details <- left_join(filter(DDI_data, drug1_name == "Apixaban" | drug1_name == "Warfarin"),
                                filter(reviews_clean, drug == "Apixaban" | drug == "Warfarin"),
                                by =  c("drug1_name" = "drug"))
```








# 
t <- c("drug1 other stuff", "drug2 other stuff 10 mg")
1 <- strgsplit(t, split = " ", fixed = TRUE)
sapply(1, function(x { x[1]})


table$colnam(sapply(strsplit))
